// Import the jsonwebtoken library
// This library is used to create and verify JSON Web Tokens (JWT)
const jwt = require("jsonwebtoken");

// Environment Setup
// Initialize dotenv and load all variables from the .env file into 'process.env'
require('dotenv').config();

// JSON Web Tokens
// A JWT is a token used for authentication that proves who you are after login.

// TOKEN CREATION
// Generate JWT Access Token for Authenticated Users 
// JWT Anatomy
    // Header (auto-generated by JWT library)
    // Payload (contains user data / claims)
    // Signature (created using the secret key)
module.exports.createAccessToken = (user) => {
    // Create a payload object that contains the user's information
    // These are called "claims" and will be stored inside the token
    const data = {
        // Store the user's unique ID
        id : user._id,
        // Store the user's email
        email : user.email,
        // Store if the user is an admin (true or false)
        isAdmin : user.isAdmin
    };
    // Generate a JWT using the payload (data), secret key (process.env.JWT_SECRET_KEY), and optional settings
    // jwt.sign() creates the token
    // 1st argument: data (payload)
    // 2nd argument: secret key (used to sign the token securely)
    // 3rd argument: options (empty for now, but can include expiration of token, etc.)
    return jwt.sign(data, process.env.JWT_SECRET_KEY, {});
};
// Middleware to Validate and Decode JWT from Request Headers
// Parameters
    // req  - contains data from the client (headers, body, params)
    // res  - used to send a response back to the client
    // next - function that passes control to the next middleware or route
// Middleware to validate and decode JWT from Request Headers
module.exports.verify = (req, res, next) => {

    // Log the Authorization header
    // Result: "Bearer <JWT>"
    console.log(req.headers.authorization);

    // Retrieve the authorization header which contains the token
    let token = req.headers.authorization;

    // Check if the token exists
if (!token) {
    return res.status(401).send({
        auth: "Failed",
        message: "No authentication token provided."
    });
} else {
        console.log(token);


        if (!token.startsWith("Bearer ")) {
    return res.status(401).send({
        auth: "Failed",
        message: "Invalid authorization format."
    });
}

        token = token.slice(7);

        console.log(token);

        jwt.verify(token, process.env.JWT_SECRET_KEY, (err, decodedToken) => {
            if (err) {
                // Sends a 403 Forbidden response
                // status(403) means the client is authenticated but not allowed to access this resource
                return res.status(403).send({
                    auth: "Failed",
                    message: err.message
                })
            // If verification success
            } else {
                console.log("result from verify method:");
                console.log(decodedToken);
                req.user = decodedToken;
                next();

            }
        })
    }

}

// Middleware to check if authenticated is an admin
module.exports.verifyAdmin = (req, res, next) => {
    if (req.user.isAdmin) {
        next();
    } else {
        // Sends a 403 Forbidden response
        // status(403) means the client is authenticated but not allowed to access this resource
        return res.status(403).send({
            auth: "Failed",
            message: "Action Forbidden"
        })
    }
}

// Error Handling Middleware
// Instead of handling errors in every route, we centralize error handling using middleware.
// This middleware catches errors from anywhere in the application.

/*
Important Note:
- In Express.js, there are 2 kinds of middleware:
    - Normal middleware
    - Error middleware
- It ensures consistent error responses across all endpoints.
- It simplifies code by letting developers focus on business logic.
- It also helps with debugging by logging errors in one place.
*/

/*
Important Note:
- In Express.js, there are 2 kinds of middleware:
    - Normal middleware (req, res, next)
    - Error middleware (err, req, res, next)
    - Error middleware has 4 parameters (with err at the start).
    - next is always included even if you don't have to use it. It must be there so Express knows it's an error handler
*/
module.exports.errorHandler = (err, req, res, next) => {

    console.error(err);

    // use err.status if available, otherwise default to 500 (Internal Server Error)
    const statusCode = err.status || 500;

    const errorMessage = err.message || 'Internal Server Error';

    // res.status.json({
    // Send JSON response with the given status code
     res.status(statusCode).json({
        errors: {
            message: errorMessage,
            errorCode: err.code || 'SERVER_ERROR',
            details: err.details || null
        }
    });
};